version: '3.8'
services:
  php:
    container_name: rotr_php
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www
    depends_on:
      - database

  httpd:
    container_name: rotr_nginx
    build:
      context: .
      dockerfile: Dockerfile-httpd
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    image: mysql:8.0
    restart: always
    container_name: rotr_mysql
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: rotr_phpmyadmin
    image: phpmyadmin:5.2.1-apache
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1

volumes:
  data-volume: {}
