version: '3.3'
services:
  php:
    container_name: rotr_php
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www
      - ./.env:/var/www/public/api/.env
    depends_on:
      - database

  httpd:
    container_name: rotr_nginx
    build:
      context: .
      dockerfile: Dockerfile-httpd
    ports:
      - '8085:80'
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    image: mysql:8.0
    restart: always
    container_name: rotr_mysql
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe

volumes:
  data-volume: {}
