name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile-php --tag my-image-name:$(date +%s)

      - name: Run the containers
        run: docker-compose --env-file ./.github/workflows/.env.workflows up -d

      - name: Check the containers status
        run: docker ps

      - name: Install the composer dependencies
        run: sh ./docker/scripts/install-composer-dependencies.sh

      - name: Wait 15s for the MySQL service to be ready for connections
        run: sleep 15

      - name: Migrate the test database
        run: sh ./docker/scripts/migrate-database-test-workflows.sh

      - name: Run the PHPUnit tests
        run: sh ./docker/scripts/run-phpunit-workflows.sh
