name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run the containers
      run: docker-compose up -d
    - name: Install the composer dependencies
      run: docker exec rotr_php composer install
    - name: Run phpunit tests
      run: docker exec rotr_php ./vendor/bin/phpunit tests
