name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run the containers
      run: docker-compose up -d

    - name: Install the composer dependencies
      run: sh ./docker/scripts/install-composer-dependencies.sh

    - name: Check the containers status
      run: docker ps

    - name: Wait 20s for the MySQL service to be ready for connections
      run: sleep 10

    - name: Migrate the test database
      run: sh ./docker/scripts/migrate-database-test.sh

    - name: Run phpunit tests
      run: sh ./docker/scripts/run-phpunit.sh
